name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR file with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR build
        run: ls -lh target/

      - name: Rename JAR to app.jar (for Docker simplicity)
        run: mv target/*.jar target/app.jar

      - name: Build Docker image
        run: docker build -t springboot-app .

      - name: Save Docker image to file
        run: docker save springboot-app -o springboot-app.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "springboot-app.tar"
          target: "~/"

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < springboot-app.tar
            docker stop springboot-app || true
            docker rm springboot-app || true
            docker run -d --name springboot-app -p 8086:8080 springboot-app
